[toc]
## 7.异常
异常:是发生在运行时期发生的不正常情况。
### 7.1 异常的概述

Throwable
1. **Error**
   1. 通常出现重大的问题如：运行的类不存在或者内存溢出等
   2. 不编写对代码对其处理
2. **Exception**
   1. 在运行时运行出现的一起情况，可以通过try catch finally

Exception和Error的子类名都是以父类名作为后缀。

在java中用类的形式对不正常情况进行了描述和封装对象。

描述不正常的情况的类，就称为异常类。

以前正常流程代码和问题处理代码相结合</br>
现在将正常的流程代码和问题处理代码进行分离，提高阅读性。

其实异常类就是java通过面向对象的思想将问题封装成了对象

用异常类对其进行描述
不同的问题用不同的类进行具体的描述，比如角标越界、空指针等等
```
class ExceptionDemo
{
    public static void main(String[]args)
    {
        int [] arr =new int[3];
        arr=null;
        System.out.println(arr[3]);
        sleep(-5);
    }
    public static void sleep(int time)
    {
        if(time<0)
        {
            throw new Futime();//就代码在时间为负的情况，这个对象中会
                    //包含着问题的名称，信息，位置等等信息
        }
        if(time>10000)
        {
            throw new BigTime()
        }
        System.out.println("我睡。。。"+time);
    }
}
```
### 7.2 异常——体系
问题很多，意味着描述的类也很多。</br>
将其共性进行向上抽取，形成了异常体系。

最终问题(不正常情况)就分为了两大类</br>
Throwable:(可抛的)无论是Error，还是异常问题，问题发生都可以抛出让调用者知道并处理。</br>
该体系的特点就在于Throwable及其所有子类都具有可抛性。</br>

其实是通过两个关键词来体现的
1. throws
2. throw</br>
凡是被这两个关键字所操作的类和对象都具备可抛性。

处理情况
1. 一般不可处理的。Error</br>
特点：是由Jvm抛出的严重性问题。这种问题发生一般不针对性处理。直接修改程序。
2. 可以处理的。Exception


特点：</br>
子类的后缀名都是用其父类名作为后缀，阅读性很强。

### 7.3 异常原理和异常抛出throw
**原理**: 当程序出现角标越界、空指针等情况时，程序会在特定的地方抛出异常类，给调用它的main函数，然后main主函数将异常抛给JVM虚拟机。

例：
```
class Demo
{
    public int method(int []arr,int index)
    {
        if(index>=arr.length)
        {
            throw new ArrayIndexOutofBoundsException("数组的角标越界啦："+index);
        }
        return arr[index];
    }
    
}
```

### 7.4 自定义异常&异常类的抛出throws
对于角标是整数不存在，可以用角标越界表示</br>
对于负数为角标的情况，准备用负数角标异常来表示。

负数的角标这种异常在java中并没有定义过。</br>
那就按照java异常的创建思想，面向对象，将负数角标进行自定义描述，并封装成对象。

这种自定义的问题描述称为自定义异常

注意：如果让一个类称为异常类，必须要继承异常体系，因为只有称为异常体系的子类才有资格具备可抛性。</br>
才可以被两个关键字所操作，throws throw

例：
```
class FuShuIndexException extends Exception//(RuntimeException 运行时的异常)
{
    FuShuIndexException(){
        
    }
    FuShuIndexException(String s){
        super(s);     //使用父类的输出字符串
    }
}
class Demo
{
    public int  method(int []arr,int index)throws FuShuIndexException    //函数声明抛出
    {
        if(arr==null)
            throw new NullPointerException("数组的引用不能为空！");
        if(index>=arr.length)
        {
            throw new ArrayIndexOutOfBoundsException("数组的角标越界了");
        }
        if(index<0)
        {
            throw new FuShuIndexException("为负数");
        }
        return arr[index];
    }
}
class ExceptionDemo3
{
    public static void main(String []args) throws FuShuIndexException
    {
        int [] arr =new int[3];
        Demo d=new Demo();
        int num=d.method(arr,-30);
        System.out.println("num="+num);
        System.out.println("over");
    }
}


```
// 未报告的异常错误FuShuIndexException; 必须对其进行捕获或声明以便抛出,要在主函数对其进行捕获或声明以便抛出

### 7.5 编译时检测异常和运行时异常的区别&throw和throws的区别
异常分类：
1. 编译时被检测异常：只要是Exception和其子类都是，除了特殊子类RuntimeException体系。
</br>这种问题一旦出现，希望在编译时就进行检测，让这种问题有对应的处理方式，这种问题可以针对性处理。
2. 编译时不检测异常(运行时异常)：就是Exception中的RuntimeException和其子类。</br>
这种问题的发生，无法让功能继续，运算无法运行，更多是因为调用的原因导致的或引发内部状态的改变导致的。</br>
那么这种问题一般不处理，直接编译通过，在运行时，让调用者调用时的程序强制停止，让调用对代码进行修正。

定义自定义异常类时，要么继承Exception,要么继承RuntimeException

throw和throws的区别
1. throw使用在函数上</br>
   throw使用在函数内
2. throws抛出的是异常类，可以抛出多个，用逗号隔开。</br>
throws 抛出的是异常对象，

### 7.6 异常——异常捕捉try Catch
异常处理的捕捉形式：</br>
这是可以对异常进行针对性处理的方式。

具体格式是：
```
try
{
    //需要被检测异常的代码。
}
catch(异常类 变量)  //该变量用于接收发生的异常对象
{
    //处理异常的代码
}
finally
{
    //一定会被执行的代码
}
```
```
这个问题如果自己不能处理，就用throws

如果自己可以处理，就用try
```
例：
```
class FuShuIndexException extends Exception
{
    FuShuIndexException()
    {
    }

    FuShuIndexException(String msg)
    {
        super(msg);
    }
}

class Demo 
{
    int method(int[] arr, int index)   throws FuShuIndexException,NullPointerException   //如果抛出了多个异常，则需要多catch
    {
        if(arr == null)
            throw new NullPointerException();
        if(index <0)
            throw new FuShuIndexException("数组角标为负数！");
        return arr[index];
    }
}


class  ExceptionDemo4
{
    public static void main(String[] args)     //如果异常自己解决不了，就抛出去throws，给虚拟机执行.printStackTrace()。
    {
        int[] arr = new int[3];

        Demo d = new Demo();    
        try
        {
                int i = d.method(null,0);        //异常抛在这里，new FuShuIndexException("数组角标为负数！");
                System.out.println(i);  

        }
        catch (FuShuIndexException f)     //接收抛来的异常对象，而不是直接给虚拟机了。
        //FuShuIndexException f = new FuShuIndexException("数组角标为负数！");
        {
            System.out.println(f.getMessage());       //可以使用异常对象，及其父类的所有方法，打印需要的异常信息
            //输出异常信息
            System.out.println(f);                 //该对象不是类型和哈希值，（f.toString()）异常对象有建立自己的独特字符串类型（可以该的，其实是默认加了toString()方法）。     //输出异常类名 + 异常信息
            f.printStackTrace();       //输出异常类名 + 异常信息 ，及其追踪输出。 注意返回值是空类型，不要直接打印。
            //jvm默认的异常处理机制就是调用异常对象的这个方法。

            System.out.println("负数角标异常！");      //自行处理方式
        } 

/*      catch()      //多异常多catch
        {

        }*/

        catch(Exception e)    //如果为了检测其他异常，父类的catch应该放最后，因为是按顺序检测。而所有异常对象都属于Exception。
        //多catch时面试会问。
        {                                           
                e.printStackTrace();
        }
        System.out.println("over");     //程序继续运行
    }
}

//通常建立日志文件用第三方工具，如 log4j(log for java)
```

多catch情况：父类的catch应该放最后，因为是按顺序检测。而所有异常对象都属于Exception。

### 7.7 异常处理原则

1. 函数内部如果抛出需要检测的异常，那么函数上必须要声明。
    否者必须在函数内用trycatch捕捉，否者编译失败。
2. 如果调用到了声明异常的函数，要么trycatch，要么throws,否者编译失败。
3. 功能内部可以解决，用catch.
解决不了，用throws告诉调用者，由调用者解决。
4. 一个功能如果抛出了多个异常，那么调用时，必须对应多个catch进行针对性的处理。
内部有几个需要检测的异常，就抛几个异常。抛出几个，就catch几个。
8.finally代码块：
1)作用举例：

连接数据库。
查询。      Exception
关闭连接。  一定要执行，放在finally代码块里。

2)代码块组合：

1.try catch finally
2.try catch(对个)    当没有必要资源需要释放时，可以不用定义finally

3.try finally
没catch就没有处理，所以还是要在函数上throws声明异常来处理。

用处：异常先不处理，但是资源得关掉。
```
void show() throws Exception
{
        try
        {
                //开启资源
                throw new Exception();
                //这里无法关闭资源，因为执行不到
        }
        finally
        {
                //关闭资源
        }
}
```
3）例子：
```
class Demo
{
    int show(int index)
    {
        if(index < 0)
            throw new ArrayIndexOutOfBoundsException("越界了！");
        int[] arr = new int[3];
        return arr[index];
    }
}


class  ExceptionDemo5
{
    public static void main(String[] args) 
    {
        Demo d = new Demo();


        try
        {
             int num = d.show(-3);
            System.out.println(num);
        }
        catch (ArrayIndexOutOfBoundsException e)
        {
                System.out.println(e.toString());
                return;                  
                //如果System.exit(0); 推出jvm，这时finally不执行
        }
        finally
        {
                System.out.println("finally");     //函数结束，也会执行
        }


        System.out.println("over");    //函数如果提前结束，不会执行
    }
}
```
 
9.异常的应用：
```
/*
异常的应用：   异常转换：不要有什么异常就抛出什么异常，要看调用者能否处理。

void addData(Data d)    throws  Exception         //不抛出数据库异常，因为调用者不懂数据库。
                                                                                        //进行异常转换，抛出调用者可以处理的异常。
{
    连接数据库。
    try
    {
        添加数据。出现异常 SQLException();
    }
    catch(SQLException e)
    {
        处理数据库异常。
        throws new Exception("数据没有添加成功");   //可以自定义异常抛出
    }
    finally
    {
        关闭数据库。
    }

}

```
毕老师用电脑上课。

问题领域中涉及两个对象。

毕老师，对象。

分析其中的问题：

比如电脑蓝屏，冒烟了。
```
*/

class LanPingException extends Exception
{
        LanPingException(String msg)
    {
            super(msg); 
    }
}

class MaoYanException extends Exception
{
        MaoYanException(String msg)
            {
                super(msg);
        }
}

class  prelectStop extends Exception
{
        prelectStop(String msg)
        {
                super(msg);
        }
}

class Computer 
{
    private int state = 2;
    void run() throws LanPingException,MaoYanException
    {
        if(state == 1)
            throw new LanPingException("电脑蓝屏了！");
        if(state == 2)
            throw new MaoYanException("电脑冒烟了！");

        System.out.println("电脑运行");
    }

    void reset()
    {
        state = 0;
        System.out.println("电脑重启");
    }
}

class Teacher
{
    private String name;
    private Computer comp;
    Teacher(String name)
    {
        this.name = name;
        comp = new Computer();
    }

    void prelect()   throws prelectStop  //  throws MaoYanException   //老师讲课抛出电脑冒烟，不合理
    {
        try
        {
            comp.run();
            System.out.println("讲课");
        }
        catch (LanPingException e)
        {
                System.out.println(e.getMessage());
                comp.reset();                              //预处理，可以自己处理，所以才设置为编译时检测异常Exception,而不是运行时异常RuntimeException
                prelect();
        }
        catch (MaoYanException e)
        {
                System.out.println(e.getMessage());
                test();
                //可以对电脑进行维修,但是不传给调用者，因为他也处理不了
                //throw e;         //冒烟异常处理不了，返回给调用者在方法声明中标识出来。
                throw new prelectStop("课程进度无法完成！原因：" + e.getMessage());        //返回调用者可以处理的异常，异常进行了转换
        }



    }

    void test()
    {
        System.out.println("做练习");
    }
}


class ExceptionDemo6 
{
    public static void main(String[] args) 
    {
        Teacher t= new Teacher("毕老师");

        try
        {
            t.prelect();
        }
        catch (prelectStop e)
        {
                System.out.println(e.getMessage());
                System.out.println("换人");

        }

    }
}

  ```
### 7.8 ====异常的注意事项====：
1. ==子类在覆盖父类方法时，父类方法如果抛出了异常，那么子类的方法只能抛出父类的异常或者该异常的子类，也可以不抛。==
2. ==如果父类抛出多个异常，那么子类只能抛出父类异常的子集==。

简单点说：如果父类的方法没有抛出异常，那么子类覆盖时绝对不能抛。（爸爸够坏了，儿子不能更坏了）

==这时如果子类还是使用了异常，只能try,不能抛。==

原因：如果在方法2中传入了父类的对象，并trycatch了父类的方法1，这时catch中是父类的异常类型。如果有一个子类覆盖了父类的

方法1，这时如果方法2中传的是子类的对象（向上转型），则先调用的是子类中覆盖的方法，这时catch中的异常类型只有是父类的异常
或者子类才不会出现问题。

举例：
```
class A extends Exception
{
}

class B extends A
{
}

class C extends Exception
{
}


class Fu
{
    void show() throws A
        {}
}

class Zi extends Fu
{
    void show() throws B    //这时应该为A或者B
    {}
}

class Test
{
    void method(Fu f)
    {
            try
            {
                f.show();
            }
            catch(A a)     
            {
            }
    }
}

class ExceptionDemo7 
{
    public static void main(String[] args) 
    {
        Test t = new Test();
//      t.method(new Fu());
        t.method(new Zi());   
    }
}
```